import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import Link from 'next/link';
import { Metadata } from 'next';
import BlogImage from './BlogImage';

export const metadata: Metadata = {
  title: 'Blog | Saunders Simmons Ltd - Web Design & SEO Insights',
  description: 'Expert insights on web design, SEO, app development, and software solutions from Saunders Simmons Ltd in Yeovil, Somerset.',
};

interface BlogPost {
  slug: string;
  title: string;
  date: string;
  excerpt: string;
  image?: string;
  readingTime?: string;
  tags?: string[];
}

// Static blog posts (existing content)
const staticBlogPosts: BlogPost[] = [
  {
    slug: 'web-design-somerset-2025',
    title: 'Professional Web Design Somerset: Why Your Business Needs a Modern Website in 2025',
    excerpt: 'Discover why Somerset businesses are investing in professional web design to stay competitive. From increased conversions to better Google rankings, learn how a modern website can transform your business.',
    date: '2025-01-08',
    image: '/logos/logo.png',
    readingTime: '5 min read',
    tags: ['Web Design Somerset', 'Professional Websites', 'Business Growth']
  },
  {
    slug: 'seo-tips-dorset-businesses',
    title: 'SEO for Dorset Businesses: 10 Local SEO Tips to Dominate Google in 2025',
    excerpt: 'Local Dorset businesses are missing out on customers every day due to poor SEO. Learn our proven strategies to rank #1 on Google and attract more local customers.',
    date: '2025-01-06',
    image: '/logos/logo.png',
    readingTime: '8 min read',
    tags: ['SEO Dorset', 'Local SEO', 'Google Rankings']
  },
  {
    slug: 'web-design-yeovil-case-study',
    title: 'Web Design Yeovil Case Study: How We Increased a Local Business\'s Revenue by 200%',
    excerpt: 'See how our professional web design services helped a Yeovil business double their online revenue. Real results, real numbers, and the strategies that made it happen.',
    date: '2025-01-04',
    image: '/logos/logo.png',
    readingTime: '6 min read',
    tags: ['Web Design Yeovil', 'Case Study', 'Business Growth']
  },
  {
    slug: 'website-redesign-roi',
    title: 'The ROI of Website Redesign: Why Somerset & Dorset Businesses See 300% Returns',
    excerpt: 'Think a website redesign is expensive? Think again. Discover why businesses across Somerset and Dorset are seeing massive returns on their web design investments.',
    date: '2025-01-02',
    image: '/logos/logo.png',
    readingTime: '7 min read',
    tags: ['Website Redesign', 'ROI', 'Somerset Business', 'Dorset Business']
  },
  {
    slug: 'mobile-first-design-2025',
    title: 'Mobile-First Web Design: Essential for Somerset & Dorset Businesses in 2025',
    excerpt: 'With 70% of local searches happening on mobile, your website must be mobile-first. Learn why responsive design is crucial for Somerset and Dorset businesses.',
    date: '2024-12-30',
    image: '/logos/logo.png',
    readingTime: '5 min read',
    tags: ['Mobile Design', 'Responsive Web Design', 'User Experience']
  },
  {
    slug: 'local-seo-yeovil-guide',
    title: 'Complete Local SEO Guide for Yeovil Businesses: Rank Above Your Competitors',
    excerpt: 'Dominate local search results in Yeovil with our comprehensive SEO guide. From Google My Business to local citations, everything you need to know.',
    date: '2024-12-28',
    image: '/logos/logo.png',
    readingTime: '10 min read',
    tags: ['Local SEO Yeovil', 'Google My Business', 'Local Rankings']
  }
];

async function getBlogPosts(): Promise<BlogPost[]> {
  // Get autogenerated posts from content/posts (where they're actually committed)
  const postsDirectory = path.join(process.cwd(), 'content/posts');
  let autoPosts: BlogPost[] = [];
  
  if (fs.existsSync(postsDirectory)) {
    const fileNames = fs.readdirSync(postsDirectory);
    
    autoPosts = fileNames
      .filter(fileName => fileName.endsWith('.md'))
      .map(fileName => {
        const fullPath = path.join(postsDirectory, fileName);
        const fileContents = fs.readFileSync(fullPath, 'utf8');
        const { data } = matter(fileContents);
        
        // Extract clean slug from filename
        const slug = fileName
          .replace(/^\d{4}-\d{2}-\d{2}-/, '') // Remove date prefix
          .replace('.md', '') // Remove extension
          .replace(/-\d+$/, ''); // Remove timestamp suffix
        
        return {
          slug: slug,
          title: data.title || 'Untitled',
          date: data.date || new Date().toISOString(),
          excerpt: data.excerpt || '',
          image: data.image,
          readingTime: data.readingTime,
          tags: data.tags || []
        };
      });
  }
  
  // Combine static and auto posts, sort by date
  const allPosts = [...staticBlogPosts, ...autoPosts]
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  
  return allPosts;
}

export default async function BlogsPage() {
  const posts = await getBlogPosts();
  
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 via-white to-blue-50">
      {/* Hero Section */}
      <section className="relative py-20 px-6">
        <div className="max-w-6xl mx-auto text-center">
          <h1 className="text-5xl md:text-6xl font-bold mb-6 bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
            Digital Insights Hub
          </h1>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            Expert guidance on web design, SEO, and digital transformation 
            from your trusted Somerset digital partner.
          </p>
        </div>
      </section>

      {/* Blog Posts Grid */}
      <section className="py-12 px-6">
        <div className="max-w-6xl mx-auto">
          {posts.length === 0 ? (
            <div className="bg-white rounded-xl shadow-lg p-12 text-center max-w-2xl mx-auto">
              <div className="w-20 h-20 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-6">
                <svg className="w-10 h-10 text-blue-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
                </svg>
              </div>
              <h2 className="text-2xl font-semibold text-gray-900 mb-3">Blog Coming Soon</h2>
              <p className="text-gray-600 text-lg">We're crafting insightful content to help you navigate the digital landscape. Check back soon for expert articles and guides!</p>
            </div>
          ) : (
            <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
              {posts.map((post) => (
                <article 
                  key={post.slug}
                  className="bg-white rounded-xl shadow-lg overflow-hidden hover:shadow-xl transition-shadow duration-300"
                >
                  {post.image && (
                    <div className="h-48 relative">
                      <BlogImage 
                        src={post.image} 
                        alt={post.title}
                        className="w-full h-full object-cover"
                      />
                    </div>
                  )}
                  
                  <div className="p-6">
                    <h2 className="text-xl font-bold mb-3 line-clamp-2">
                      <Link 
                        href={`/blogs/${post.slug}`}
                        className="text-gray-900 hover:text-blue-600 transition-colors"
                      >
                        {post.title}
                      </Link>
                    </h2>
                    
                    <p className="text-gray-600 mb-4 line-clamp-3">
                      {post.excerpt}
                    </p>
                    
                    <div className="flex justify-between items-center text-sm text-gray-500">
                      <span>{new Date(post.date).toLocaleDateString('en-GB')}</span>
                      {post.readingTime && <span>{post.readingTime}</span>}
                    </div>
                    
                    {post.tags && post.tags.length > 0 && (
                      <div className="mt-4 flex flex-wrap gap-2">
                        {post.tags.slice(0, 3).map((tag) => (
                          <span 
                            key={tag}
                            className="text-xs bg-blue-100 text-blue-700 px-2 py-1 rounded"
                          >
                            {tag}
                          </span>
                        ))}
                      </div>
                    )}
                  </div>
                </article>
              ))}
            </div>
          )}
        </div>
      </section>
    </div>
  );
}