// Email-safe shared design. Keep this file identical across active SEO workers.
export const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const e = escapeHtml;
const number = value => typeof value === 'number' && Number.isFinite(value) ? value.toLocaleString('en-GB', { maximumFractionDigits: 1 }) : '—';
const safeUrl = value => { try { const url = new URL(value); return ['https:', 'http:'].includes(url.protocol) ? e(url.href) : ''; } catch { return ''; } };
const dateLabel = value => new Date(value).toLocaleDateString('en-GB', { timeZone: 'Europe/London', day: 'numeric', month: 'long', year: 'numeric' });
const total = (rows, key) => rows.length && rows.every(row => typeof row[key] === 'number' && Number.isFinite(row[key])) ? rows.reduce((sum, row) => sum + row[key], 0) : null;
const heading = title => `<h2 style="margin:0 0 16px;font-size:19px;line-height:1.35;color:#142e38;">${e(title)}</h2>`;
const paragraph = text => `<p style="margin:0 0 12px;font-size:14px;line-height:1.7;color:#52636a;overflow-wrap:anywhere;">${e(text)}</p>`;
const section = content => `<tr><td class="pad" style="padding:28px 32px;border-bottom:1px solid #edf0ed;">${content}</td></tr>`;
const button = (label, url, dark = true) => safeUrl(url) ? `<table role="presentation" cellpadding="0" cellspacing="0" style="margin-top:18px;"><tr><td bgcolor="${dark ? '#142e38' : '#eff3ef'}" style="border-radius:6px;"><a href="${safeUrl(url)}" style="display:inline-block;padding:13px 20px;font-size:13px;font-weight:bold;color:${dark ? '#ffffff' : '#142e38'};text-decoration:none;">${e(label)} &rarr;</a></td></tr></table>` : '';
const stats = values => `<table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr>${values.map(([value, label], i) => `<td class="stat" width="33%" valign="top" style="padding:0 12px ${i ? '0 18px' : '0 0'};${i ? 'border-left:1px solid #e1e7e3;' : ''}"><div style="font-size:30px;line-height:1.2;font-weight:bold;letter-spacing:-1px;color:#142e38;">${e(number(value))}</div><div style="padding-top:7px;font-size:12px;line-height:1.5;color:#66766c;">${e(label)}</div></td>`).join('')}</tr></table>`;
function article(post, site) {
  const slug = post.slug;
  const url = post.url || (slug && /^[a-z0-9][a-z0-9-]*$/.test(slug) ? `${site.url}/blog/${slug}${site.blogTrailingSlash ? '/' : ''}` : null);
  return `<div style="padding:22px;background:#f0f5ed;border:1px solid #dce6d7;border-radius:8px;margin-bottom:12px;"><div style="font-size:11px;letter-spacing:1.4px;font-weight:bold;text-transform:uppercase;color:#526a41;">${post.isRefresh ? 'Article refreshed' : 'Article published'}${post.date ? ' &middot; ' + e(dateLabel(post.date)) : ''}</div><h3 style="margin:12px 0 8px;font-size:22px;line-height:1.35;letter-spacing:-0.3px;color:#142e38;">${e(post.title)}</h3>${post.targetKeyword ? paragraph('Focus: ' + post.targetKeyword) : ''}${button('Read the article', url)}</div>`;
}
function actions(recommendations) {
  if (!recommendations.length) return paragraph('No new recommendations were recorded. The full run history is available in the dashboard.');
  return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0">${recommendations.slice(0, 3).map((rec, i) => `<tr><td width="36" valign="top" style="padding:3px 12px 18px 0;"><div style="font-size:17px;font-weight:bold;color:#cb683d;">0${i + 1}</div></td><td valign="top" style="padding-bottom:18px;"><div style="font-size:14px;font-weight:bold;color:#142e38;line-height:1.5;">${e(rec.title || rec.recommendation)}</div>${rec.description || rec.reasoning ? `<div style="margin-top:5px;font-size:13px;line-height:1.6;color:#617078;">${e(rec.description || rec.reasoning)}</div>` : ''}</td></tr>`).join('')}</table>`;
}
function keywords(rows) {
  const observed = rows.filter(row => typeof row.position === 'number' && Number.isFinite(row.position)).sort((a,b) => (b.impressions || 0) - (a.impressions || 0)).slice(0, 6);
  if (!observed.length) return paragraph('No positions were returned for the tracked queries in this snapshot. Page indexing needs a separate check.');
  return `<table width="100%" cellpadding="0" cellspacing="0" style="font-size:13px;border-collapse:collapse;"><tr><th align="left" style="padding:0 12px 10px 0;font-size:11px;color:#7c8882;font-weight:normal;">TRACKED QUERY</th><th align="right" style="padding-bottom:10px;font-size:11px;color:#7c8882;font-weight:normal;">AVG. POSITION</th></tr>${observed.map(row => {
    const match = String(row.previousPosition || '').match(/Position ([\d.]+)/);
    const delta = match ? Number(match[1]) - row.position : null;
    const change = delta !== null && Math.abs(delta) >= 0.1 ? `<div style="font-size:11px;font-weight:normal;color:${delta > 0 ? '#587545' : '#a45a40'};">${delta > 0 ? 'Up' : 'Down'} ${number(Math.abs(delta))}</div>` : '';
    return `<tr><td style="padding:12px 12px 12px 0;border-top:1px solid #edf0ed;line-height:1.5;">${e(row.keyword)}<div style="font-size:11px;color:#7c8882;">${number(row.impressions)} impressions &middot; ${number(row.clicks)} clicks</div></td><td align="right" valign="top" style="padding:12px 0;border-top:1px solid #edf0ed;font-size:16px;font-weight:bold;color:#142e38;">${number(row.position)}${change}</td></tr>`;
  }).join('')}</table>`;
}
function competitors(items) {
  return items.slice(0,3).map(item => `<p style="margin:0 0 10px;font-size:13px;line-height:1.6;color:#617078;"><strong style="color:#142e38;">${e(item.name || item.domain)}</strong><br>${item.error ? 'Sitemap check unavailable.' : `${e(number(item.totalPages))} sitemap URLs observed${item.recentPages?.length ? ` · ${e(number(item.recentPages.length))} newly observed URLs` : ''}`}</p>`).join('') + paragraph('Sitemap observations do not confirm indexing or when an article was published.');
}
function shell(site, {title, eyebrow, date, preheader, body}) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>${e(site.name)} SEO update</title><style>@media only screen and (max-width:600px){.outer{padding:12px 6px!important}.pad{padding:24px 22px!important}.hero-title{font-size:29px!important}.stat{display:block!important;width:auto!important;border-left:0!important;border-bottom:1px solid #e1e7e3;padding:12px 0!important}.container{width:100%!important}}</style></head><body style="margin:0;padding:0;background:#f3f2ec;font-family:Arial,Helvetica,sans-serif;color:#142e38;"><div style="display:none;font-size:1px;color:#f3f2ec;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden;mso-hide:all;">${e(preheader)}</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0" bgcolor="#f3f2ec"><tr><td class="outer" align="center" style="padding:30px 12px;"><!--[if mso]><table role="presentation" width="640"><tr><td><![endif]--><table class="container" role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:640px;background:#ffffff;border:1px solid #e3e6df;border-radius:12px;overflow:hidden;"><tr><td class="pad" bgcolor="#142e38" style="padding:32px;color:#ffffff;border-top:5px solid #d78051;"><table role="presentation" width="100%"><tr><td style="font-size:15px;font-weight:bold;color:#ffffff;">${e(site.name)}</td><td align="right" style="font-size:11px;letter-spacing:1.4px;color:#bbcac8;">PAIGE / SEO</td></tr></table><div style="margin-top:34px;font-size:11px;letter-spacing:1.8px;text-transform:uppercase;color:#d5b79c;">${e(eyebrow)}</div><h1 class="hero-title" style="margin:10px 0 12px;font-size:36px;line-height:1.13;letter-spacing:-1px;color:#ffffff;">${e(title)}</h1><p style="margin:0;font-size:13px;color:#bbcac8;line-height:1.6;">${e(date)}</p></td></tr>${body}${section(heading('Your SEO, in one place.') + paragraph('Open the dashboard for the full keyword set, report history and completed work.') + button('Open SEO dashboard','https://seo.saunders-simmons.co.uk'))}<tr><td class="pad" bgcolor="#f8f8f3" style="padding:22px 32px;"><p style="margin:0;font-size:12px;line-height:1.7;color:#768078;">Sent by Paige SEO &middot; Saunders Simmons<br>${safeUrl(site.url) ? `<a href="${safeUrl(site.url)}" style="color:#52645a;text-decoration:underline;">${e(site.url.replace(/^https?:\/\//,''))}</a>` : ''}</p></td></tr></table><!--[if mso]></td></tr></table><![endif]--></td></tr></table></body></html>`;
}
export function renderRunReport(site, data, reportDate = new Date()) {
  const rows = data.rankings || [];
  const available = data.measurementAvailable !== false;
  const articles = data.articles || (data.blogPost ? [data.blogPost] : []);
  const title = articles.length ? (articles[0].isRefresh ? 'A fresh look at your content.' : 'Your latest article is ready.') : 'Your SEO update.';
  const summary = data.sessionSummary || 'The latest SEO observations are ready to review.';
  const note = data.window ? `Query window: ${data.window.startDate} to ${data.window.endDate}.` : 'Query metrics use the latest logged 28-day Search Console snapshot.';
  let body = section(heading(articles.length ? 'Content completed' : 'Work completed') + articles.slice(-6).map(post => article(post, site)).join('') + paragraph(summary) + (data.linksAdded > 0 ? paragraph(`${data.linksAdded} internal links added during this run.`) : ''));
  if (data.monthlyStats) body += section(stats(data.monthlyStats));
  body += section(heading('Search at a glance') + stats([[available ? total(rows,'clicks') : null,'Tracked query clicks'],[available ? total(rows,'impressions') : null,'Tracked query impressions'],[available ? rows.filter(row => typeof row.position === 'number' && Number.isFinite(row.position)).length : null,'Queries with a position']]) + `<p style="margin:18px 0 0;font-size:11px;line-height:1.6;color:#7c8882;">${e(note)} These are tracked queries, rather than full-site totals. Missing query data does not establish indexing status.${available ? '' : ' Search Console data is currently unavailable.'}</p>`);
  body += section(heading('Next priorities') + actions(data.recommendations || []));
  body += section(heading('Queries to keep an eye on') + (available ? keywords(rows) : paragraph('Search Console data was unavailable. Review the worker log to restore measurement access.')) + `<p style="margin:14px 0 0;font-size:11px;line-height:1.6;color:#7c8882;">Up to six observed queries, ordered by impressions. Average positions are observations; snapshot comparisons can overlap.</p>`);
  const comps = data.competitorReport?.competitors || [];
  if (comps.length) body += section(heading('Competitor watch') + competitors(comps));
  const html = shell(site, { title: data.title || title, eyebrow: data.monthlyStats ? 'Monthly review' : 'SEO progress report', date: dateLabel(reportDate), preheader: summary, body });
  const text = `${site.name} — ${data.monthlyStats ? 'Monthly SEO review' : 'SEO update'} — ${dateLabel(reportDate)}\n\n${summary}\n\n${articles.map(post => `${post.isRefresh ? 'Refreshed' : 'Published'}: ${post.title}${post.slug ? `\n${site.url}/blog/${post.slug}${site.blogTrailingSlash ? '/' : ''}` : ''}`).join('\n\n')}\n\n${note}\nTracked query clicks: ${number(available ? total(rows,'clicks') : null)}\nTracked query impressions: ${number(available ? total(rows,'impressions') : null)}\n\nNext priorities:\n${(data.recommendations || []).slice(0,3).map(rec => `${rec.title || rec.recommendation}\n${rec.description || rec.reasoning || ''}`).join('\n\n')}\n\n${rows.map(row => `${row.keyword}: position ${number(row.position)}, ${number(row.clicks)} clicks, ${number(row.impressions)} impressions`).join('\n')}\n\nQuery absence does not establish indexing status.\nFull report history: https://seo.saunders-simmons.co.uk`;
  return { html, text };
}
export function renderMonthlyReport(site, runs, reportDays = 30, reportDate = new Date()) {
  const successful = runs.filter(run => run.status === 'success').sort((a,b) => a.created_at.localeCompare(b.created_at));
  if (!successful.length) throw new Error('No successful runs found in the reporting window');
  const latest = successful.at(-1);
  const articles = [...new Map(successful.filter(run => run.blog_post_title).map(run => [run.blog_post_slug || run.blog_post_title, {title:run.blog_post_title, targetKeyword:run.blog_post_keyword, slug:run.blog_post_slug, isRefresh:run.blog_post_is_refresh, date:run.created_at}])).values()];
  return renderRunReport(site, { title:'Your month in search.', rankings:latest.rankings_data || [], articles, recommendations:latest.recommendations || [], competitorReport:{competitors:latest.competitor_data || []}, monthlyStats:[[successful.length,'Successful SEO runs'],[articles.length,'Articles published / refreshed'],[successful.reduce((sum,run)=>sum+(run.links_added || 0),0),'Internal links added']], sessionSummary:`Over the last ${reportDays} days, ${successful.length} successful SEO runs were recorded, with ${articles.length} distinct articles published or refreshed.${runs.some(run => run.status === 'error') ? ` ${runs.filter(run => run.status === 'error').length} unsuccessful runs were also logged; see the dashboard.` : ''} ${latest.session_summary || ''}` }, reportDate);
}
